<?php
/**
 * @file Code handle collections features
 */

/**
 * Implements hook_menu().
 */
function ding_collection_reservation_menu() {
  $items['ting/collection/%ting_collection/popup/nojs'] = array(
    'page callback' => 'ding_collection_reservation_ajax',
    'page arguments' => array(4, 2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['ting/collection/%ting_collection/popup/ajax'] = array(
      'delivery callback' => 'ajax_deliver',
    ) + $items['ting/collection/%ting_collection/popup/nojs'];

  return $items;
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add configuration to admin reservable settings form
 */
function ding_collection_reservation_form_ting_admin_reservable_settings_alter(&$form, &$form_state, $form_id) {
  //Add check box for reservable collections
  $form['ting_reservable']['ting_reservable_collections'] = array(
    '#type'          => 'checkboxes',
    '#title'         => t('Collections'),
    '#options'       => drupal_map_assoc(array(t('Yes, show a Reserve-button on collections.'))),
    '#default_value' => variable_get('ting_reservable_collections', array()),
    '#weight'        => -1
  );
}

/**
 * Implements hook_js_alter().
 */
function ding_collection_reservation_js_alter(&$javascript) {
  $ding_availability_js = drupal_get_path('module', 'ding_availability') . '/js/ding_availability.js';
  $args = arg();
  if ((!empty($args[3]) && $args[3] === 'popup') && (!empty($args[4]) && $args[4] === 'ajax') && isset($javascript[$ding_availability_js])) {
    unset($javascript[$ding_availability_js]);
  }
  elseif ($args[0] == 'search' && $args[1] == 'ting') {
    drupal_add_js(drupal_get_path('module', 'ding_collection_reservation') . '/js/ding_collection_reservation.js', 'file');
    drupal_add_css(drupal_get_path('module', 'ding_collection_reservation') . '/css/ding_collection_reservation.css', 'file');
  }
}

/**
 * Menu entry callback.
 *
 * @param TingCollection $collection
 *   Ting collection.
 * @param $type
 *   Type of callback.
 *
 * @return
 *   Array of ajax commands.
 */
function ding_collection_reservation_ajax($type, TingCollection $collection) {
  $commands = array();
  $ajax = ($type == 'ajax');

  // If there is only one item that can eb reserved
  // we should reserve it on the fly.
  if (count($collection->getEntities()) == 1) {
    return ding_reservation_reserve_ajax(reset($collection->getEntities()));
  }

  if ($ajax) {
    $view = ting_collection_view($collection, 'collection_popup');
    $output = render($view);
    $commands[] = ajax_command_ding_popup('collection_reservation', t('Reserve'), $output);
    drupal_add_js(drupal_get_path('module', 'ding_collection_reservation') . '/js/ding_collection_reservation.js', 'file');
  }
  else {
    // Simple redirect with anchor. Better solution is needed here.
    drupal_goto('ting/collection/' . $collection->id, array('fragment' => 'collection_items'));
  }

  return array(
    '#type' => 'ajax',
    '#commands' => $commands,
  );
}

/**
 * Implements hook_entity_info_alter().
 */
function ding_collection_reservation_entity_info_alter(&$entity_info) {
  if (!isset($entity_info['ting_object']['view modes']['objects_in_popup'])) {
    $entity_info['ting_object']['view modes'] += array(
      'objects_in_popup' => array(
        'label' => t('List of objects in popup'),
        'custom settings' => TRUE,
      ),
    );
  }
  if (!isset($entity_info['ting_collection']['view modes']['collection_popup'])) {
    $entity_info['ting_collection']['view modes'] += array(
      'collection_popup' => array(
        'label' => t('Collection popup'),
        'custom settings' => TRUE,
      ),
    );
  }
}

/**
 * Implements hook_theme().
 */
function ding_collection_reservation_theme() {
  return array(
    'ting_object' => array(
      'template' => 'ting_object',
      'render element' => 'elements',
      'file' => 'ding_collection_reservation.theme.inc',
    ),
  );
}

/**
 * Implements hook_theme_registry_alter().
 */
function ding_collection_reservation_theme_registry_alter(&$theme_registry) {
  $path = drupal_get_path('module', 'ding_collection_reservation');
  $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $path);
  $theme_registry['ting_object__view_mode__objects_in_popup']['path'] = $path . '/templates';
  $theme_registry['ting_object__view_mode__objects_in_popup'] = array_merge(
    $theme_registry['ting_object__view_mode__objects_in_popup'],
    $template_file_objects['ting_object__view_mode__objects_in_popup']
  );
  $theme_registry['ting_object__view_mode__objects_in_popup']['type'] = 'module';
}
